### ISSUE TITLE
Final Label Sets - MIMIC-IV-ECG-Ext-ICD

### ISSUE THREAD

**Issue by parthagrawal02** [AI4HealthUOL/ECG-MIMIC#2]
Hey, so when I tried calculating the number of codes occurring more than 2000, my results came out to be  - 523, and not 1076

"The final label sets are selected by discarding codes occurring less than 2000 times in the dataset, resulting in a label set comprising 1076 3- to 5-digit ICD-10-CM codes for training."

Also, I am attaching the code I used(I got it from your repo):

`
import ast
import numpy as np
import pandas as pd

def flatten(l):
    return [item for sublist in l for item in sublist]  

df = pd.read_csv('physionet.org/files/mimic-iv-ecg-ext-icd-labels/1.0.0/records_w_diag_icd10.csv')

df['all_diag_all'] = df['all_diag_all'].apply(lambda x: ast.literal_eval(x))
min_cnt = 2000
col_flat = flatten(np.array(df["all_diag_all"]))
codes,counts = np.unique(col_flat,return_counts=True)
idxs = np.argsort(counts)[::-1]
codes = codes[idxs]
counts = counts[idxs]
codes=codes[np.where(counts>=min_cnt)[0]]
lbl_itos=codes
len(lbl_itos)

`

Can you help me, if I am missing something here??

Thanks 
Regards

**Comment by juanlopezcode** [comment]
Hi, it seems you are doing some custom processing steps, please check under https://github.com/AI4HealthUOL/ECG-MIMIC/blob/main/src/demo.ipynb a clear example of how to approach this, it should work 
(you should use the prepare_mimic_ecg function)
