### ISSUE TITLE
Step 3 in full_preprocessing.py

### ISSUE THREAD

**Issue by Qhan-Hu** [AI4HealthUOL/ECG-MIMIC#4]
Hi, sorry for bothering you. When I reproduced the preproceesing method according to your instruction, the following error occurred.
![1724488124833](https://github.com/user-attachments/assets/5815ef2e-a44f-46e2-aea1-50d83093362d)
The script encountered such error when it was about to complete after 9 hours of execution. I do not know how to fix it.
Could you please give me some advices? Thanks so much.

**Comment by juanlopezcode** [comment]
Hi, sorry late reply, I have updated stratify.py, it should work now.
